travis:
  secure:
    BINSTAR_TOKEN: XWDajeJiczorK8rrswUtb3FM2aIdioSgGoguyo09TSCHAaJOpmTqweODP/kQqXaSR7SFdlrfwCvDSwugJ9yCR4QbIw65Acwu2tAHGU2YA4tRmtqxdRNb02RTJTnCV3kF9SknoHCU+/WpayLBmAsuKTTqQdN2/NYVvALToZ+MJfIsMQt6MGVcaNtZcjSCIlAEMwG9R5cYZCgPXgFvx7oxLWsMX5JCyoRU9crSURbRy3vije1W1NIEBg6DCcsuvnv8I0h2R/L6Bu3xxLLyIe4LorIjttDWdTBX7bWjf8/smW2SpR4YM52wrPGta75T24O8peVBDQNhV8w+EE5w9WFowmm4u+OdwWsGH5StAe0KeTazXZFhTNlFPeGExYAe9NMLMsu38S7o+zoAPMVZXUQE0hvbBpAQpgnGCbo60+B1yUMOzyF9fs1IFtV7QzwRQ8FRr7Vas8L61vDekNgY2BBT8Dhf+KIUbRIywy0d0f27jvInMz8BN+Hk/TWKFcc8KJxUo48qnO+LYUuDeqti5r2y/MtC11YsiwKt6Onn9qlVJgAHX81EC8HEGquFx2ZcdDyLcqXMetZRABx5hKo5Gh2CUWMVSYd+QPt2QViE7Uk0wFcQoaZo5VI0DJhJlFfdh45B+4EdffsZ8vrv4gOTILuyo0ZroayRBc4Pfs4sYpWo5M4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
